import { Header } from '@/components/header'
import { inter, orbitron } from '@/lib/fonts'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} ${orbitron.variable}`}>
        <div className="flex min-h-full flex-col">
          <Header />

          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  )
}
